# SAC训练配置

algorithm: SAC
total_timesteps: 400000
eval_freq: 10000
n_eval_episodes: 10
log_freq: 10000
enable_debug_callback: true

model_kwargs:
  learning_rate: 0.0003
  buffer_size: 100000
  learning_starts: 1000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  ent_coef: auto
  policy_kwargs:
    net_arch: [128, 256, 256, 128]

